import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { languages } from "../i18n/settings";
import { Theme } from "@radix-ui/themes";
import SidebarPage from "./sidebar/page";
import NavbarPage from "./navbar/page";
import { dir } from "i18next";
import FooterPage from "./Footer/page";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
// const languages = ["en", "ja"];
const inter = Inter({ subsets: ["latin"] });
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}
export default async function RootLayout({
  children,
  params: { lng },
}: RootLayoutProps) {
  const session = await auth();
  // console.log(session);
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        {session ? (
          <div className="flex flex-col h-screen">
            <div className="flex">
              <SidebarPage params={{ lng }} />
              <div className="flex-1 ">
                <NavbarPage params={{ lng }} />
                <SessionProvider>{children}</SessionProvider>
              </div>
            </div>
          </div>
        ) : (
          <div>{children}</div>
        )}
        {/* <div className="flex flex-col h-screen">
          <div className="flex">
            <SidebarPage params={{ lng }} />
            <div className="flex-1 ">
              <NavbarPage params={{ lng }} />
              <SessionProvider>{children}</SessionProvider>
            </div>
          </div>
        </div> */}
        <Toaster />
      </body>
    </html>
    // <html lang={lng} dir={dir(lng)}>
    //   <body className={inter.className}>{children}</body>
    // </html>
  );
}
